import oracledb
import os
import sys

# Add the project root to the Python path to allow importing 'local_config'
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

try:
    import local_config as secrets
except ImportError:
    print("Error: local_config.py not found. Please create it with your database credentials.")
    sys.exit(1)

# --- SQL Commands from DATABASE.md ---

CREATE_TABLE_STATEMENTS = [
    """
    CREATE TABLE operators (
        operator_name VARCHAR2(100) NOT NULL PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE ACTORS (
        USERNAME VARCHAR2(100) NOT NULL PRIMARY KEY,
        OWNER_OPERATOR VARCHAR2(100),
        STATUS VARCHAR2(50) DEFAULT 'active',
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_actor_operator FOREIGN KEY (OWNER_OPERATOR) REFERENCES operators(operator_name)
    )
    """,
    """
    CREATE TABLE PROSPECTS (
        TARGET_USERNAME VARCHAR2(255) NOT NULL PRIMARY KEY,
        STATUS VARCHAR2(50) DEFAULT 'new',
        OWNER_ACTOR VARCHAR2(100),
        NOTES VARCHAR2(4000),
        FIRST_CONTACTED TIMESTAMP,
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_prospect_owner FOREIGN KEY (OWNER_ACTOR) REFERENCES ACTORS(USERNAME)
    )
    """,
    """
    CREATE TABLE OUTREACH_LOGS (
        LOG_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        TARGET_USERNAME VARCHAR2(255),
        ACTOR_USERNAME VARCHAR2(100),
        MESSAGE_TEXT VARCHAR2(4000),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_log_target FOREIGN KEY (TARGET_USERNAME) REFERENCES PROSPECTS(TARGET_USERNAME),
        CONSTRAINT fk_log_actor FOREIGN KEY (ACTOR_USERNAME) REFERENCES ACTORS(USERNAME)
    )
    """
]

CREATE_INDEX_STATEMENTS = [
    "CREATE INDEX idx_logs_date ON OUTREACH_LOGS(CREATED_AT)",
    "CREATE INDEX idx_logs_actor ON OUTREACH_LOGS(ACTOR_USERNAME)",
    "CREATE INDEX idx_prospects_updated ON PROSPECTS(LAST_UPDATED)"
]

SEED_DATA_STATEMENTS = [
    "INSERT INTO operators (operator_name) VALUES ('Admin')",
    "INSERT INTO ACTORS (USERNAME, OWNER_OPERATOR, STATUS) VALUES ('test_account', 'Admin', 'active')"
]

def initialize_schema():
    """
    Connects to the Oracle database and executes the DDL and DML statements
    to create the required schema for the application.
    Includes error handling to prevent crashes if objects already exist.
    """
    wallet_location = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'assets', 'wallet'))
    
    if not os.path.exists(wallet_location) or not os.listdir(wallet_location):
        print(f"Error: Wallet directory is empty or not found at {wallet_location}")
        print("Please run the setup wizard to import the wallet first.")
        return

    try:
        print("Connecting to the database...")
        with oracledb.connect(
            user=secrets.DB_USER,
            password=secrets.DB_PASSWORD,
            dsn=secrets.DB_DSN,
            config_dir=wallet_location
        ) as connection:
            print("Connection successful.")
            with connection.cursor() as cursor:
                
                # --- Create Tables ---
                print("\nCreating tables...")
                for statement in CREATE_TABLE_STATEMENTS:
                    try:
                        cursor.execute(statement)
                        table_name = statement.split("CREATE TABLE ")[1].split(" ")[0].strip()
                        print(f"  - Table '{table_name}' created successfully.")
                    except oracledb.DatabaseError as e:
                        if "ORA-00955" in str(e): # Name is already used by an existing object
                            table_name = statement.split("CREATE TABLE ")[1].split(" ")[0].strip()
                            print(f"  - Table '{table_name}' already exists. Skipping.")
                        else:
                            raise # Re-raise other database errors

                # --- Create Indexes ---
                print("\nCreating indexes...")
                for statement in CREATE_INDEX_STATEMENTS:
                    try:
                        cursor.execute(statement)
                        index_name = statement.split("CREATE INDEX ")[1].split(" ")[0].strip()
                        print(f"  - Index '{index_name}' created successfully.")
                    except oracledb.DatabaseError as e:
                        if "ORA-00955" in str(e): # Name is already used by an existing object
                             index_name = statement.split("CREATE INDEX ")[1].split(" ")[0].strip()
                             print(f"  - Index '{index_name}' already exists. Skipping.")
                        else:
                            print(f"Warning: Failed to create index. {e}")

                # --- Insert Seed Data ---
                print("\nInserting seed data...")
                for statement in SEED_DATA_STATEMENTS:
                    try:
                        cursor.execute(statement)
                        table_name = statement.split("INSERT INTO ")[1].split(" ")[0].strip()
                        print(f"  - Seed data for '{table_name}' inserted.")
                    except oracledb.DatabaseError as e:
                        if "ORA-00001" in str(e): # Unique constraint violated
                            table_name = statement.split("INSERT INTO ")[1].split(" ")[0].strip()
                            print(f"  - Seed data for '{table_name}' likely already exists. Skipping.")
                        elif "ORA-02291" in str(e): # Parent key not found
                             print(f"  - Warning: Could not insert seed data due to missing parent key. {e}")
                        else:
                            raise
                
                # --- Commit Transaction ---
                connection.commit()
                print("\nDatabase initialization complete. All changes have been committed.")

    except oracledb.Error as e:
        print(f"Database connection or setup failed: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == '__main__':
    initialize_schema()
